#ifndef CODE_GENERATOR_H
#define CODE_GENERATOR_H

enum MetaType; // @Note: Auto-generated by code_generator.cpp

// @TODO: Auto-generate these too?
enum MemberDefinitionFlag {
    MetaMemberFlag_IsPointer = 0x1,
};

struct MemberDefinition {
    u32 flags;
    MetaType type;
    char* name;
    u32 offset;
};

#define introspect(...)
#define import(type, name) union { type name; struct { BodyOf_##type }; };

#endif /* CODE_GENERATOR_H */
